extends: default
rules:
  line-length:
    max: 200
    level: warning
  comments:
    min-spaces-from-content: 1
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']
    level: warning
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false
  braces:
    max-spaces-inside: 1
    level: warning
  brackets:
    max-spaces-inside: 1
    level: warning
  document-start: disable
  new-line-at-end-of-file: enable
  trailing-spaces: enable
